# 🚢 Titanic Veri Seti Analizi Ödevi

Bu ödevde Titanic veri seti üzerinde pandas kütüphanesi kullanarak veri analizi yapacaksınız. Sorular kolay seviyeden başlayarak zorlaşmaktadır.

## 📋 Ödev Kuralları:
- Her soruyu ayrı bir hücrede çözün
- Kodlarınızı açıklayıcı yorumlarla destekleyin
- Sonuçları yorumlayın
- Grafik çizilebilecek yerlerde görselleştirme yapın

## 📊 Veri Seti Hakkında:
Titanic veri seti, 1912'de batan Titanic gemisindeki yolcular hakkında bilgi içerir.

**Sütun Açıklamaları:**
- `survived`: Hayatta kalma durumu (0 = Hayır, 1 = Evet)
- `pclass`: Yolcu sınıfı (1 = 1. sınıf, 2 = 2. sınıf, 3 = 3. sınıf)
- `sex`: Cinsiyet
- `age`: Yaş
- `sibsp`: Gemide bulunan kardeş/eş sayısı
- `parch`: Gemide bulunan ebeveyn/çocuk sayısı
- `ticket`: Bilet numarası
- `fare`: Bilet ücreti
- `cabin`: Kabin numarası
- `embarked`: Bindiği liman (C = Cherbourg, Q = Queenstown, S = Southampton)

---
# ✅ TEMEL SEVİYE SORULAR (KOLAY)
---

### Soru 1: Veri setinde kaç satır ve kaç sütun olduğunu bulun.

In [3]:
# Kodunuzu buraya yazın
# Pandas kütüphanesini içe aktar
import pandas as pd

# Titanic veri setini GitHub'dan oku ve DataFrame'e yükle
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

# Veri setinin boyutunu göster (satır sayısı, sütun sayısı)
df.shape

(891, 12)

### Soru 2: Tüm sütun isimlerini yazdırın.

In [4]:
# Kodunuzu buraya yazın
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### Soru 3: Yaş ortalamasını ve medyanını hesaplayın.

In [5]:
# Kodunuzu buraya yazın
# Yaş sütununun ortalamasını hesapla
yas_ortalama = df['Age'].dropna().mean() #eksik verileri silip ortalamasini aldik

# Yaş sütununun medyanını hesapla
yas_medyan = df['Age'].dropna().median()   # dropna()
print(f"Yaş ortalaması: {yas_ortalama:.2f}")
print(f"Yaş medyanı: {yas_medyan:.2f}")

Yaş ortalaması: 29.70
Yaş medyanı: 28.00

Ortalama ve Medyanımız birbirine yakın olduğu için burada aykırı veri görme ihtimalimiz düşük.

### Soru 4: Cinsiyet değişkenindeki eşsiz değerleri yazdırın.

In [6]:
# Kodunuzu buraya yazın
uniqueGender = df['Sex'].unique()
print(uniqueGender)

['male' 'female']

### Soru 5: `pclass` değişkenindeki değerlerin yüzdesel dağılımını yazdırın.

In [7]:
# Kodunuzu buraya yazın
pclass_numbers = df['Pclass'].value_counts()
print(pclass_numbers)

pclass_numbers = df['Pclass'].value_counts(normalize=True)
print(pclass_numbers)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64
Pclass
3    0.551066
1    0.242424
2    0.206510
Name: proportion, dtype: float64

### Soru 6: Yaşı 30'dan büyük kadın yolcuları listeleyin.

In [8]:
# Kodunuzu buraya yazın
df[(df['Age']>30) & (df['Sex']=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

### Soru 7: Yaşı 18'den küçük olup 1. sınıfta yolculuk eden yolcuları listeleyin.

In [9]:
# Kodunuzu buraya yazın
df[(df['Age']< 18)& (df['Pclass']==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
504,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S

### Soru 8: İlk 10 gözlemden son 3'ünü gösterin.

In [10]:
# Kodunuzu buraya yazın
df.head(10).tail(3) #?????????????????????? mantıklı mı bilmiyorum

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Soru 9: Bilet fiyatı (fare) 100'den büyük olan kaç kişi vardır?

In [11]:
# Kodunuzu buraya yazın
df[df['Fare']>100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

### Soru 10: `sex`, `age` ve `fare` sütunlarından oluşan yeni bir DataFrame oluşturun.

In [12]:
# Kodunuzu buraya yazın
df_new = df.copy()
df_new = df_new[['Sex','Age','Fare']]
df_new

        Sex   Age     Fare
0      male  22.0   7.2500
1    female  38.0  71.2833
2    female  26.0   7.9250
3    female  35.0  53.1000
4      male  35.0   8.0500
..      ...   ...      ...
886    male  27.0  13.0000
887  female  19.0  30.0000
888  female   NaN  23.4500
889    male  26.0  30.0000
890    male  32.0   7.7500

[891 rows x 3 columns]

---
# ⚙️ ORTA SEVİYE SORULAR
---

### Soru 1: Cinsiyete göre yaş ortalamasını bulun.

In [13]:
# Kodunuzu buraya yazın
df.groupby('Sex').agg({'Age':'mean'})

              Age
Sex
female  27.915709
male    30.726645

### Soru 2: Sınıfa göre hayatta kalan kişi sayısını bulun.

In [14]:
# Kodunuzu buraya yazın
df.groupby('Pclass').agg({'Survived':'sum'})

        Survived
Pclass
1            136
2             87
3            119

Burada `sum` fonksiyonu kullanmamın sebebi 0'ın -yani 💀 olanlar - toplama işlemine etkisi olmamasıdır.

### Soru 3: Hem cinsiyet hem sınıfa göre hayatta kalma oranlarını hesaplayın.

In [15]:
# Kodunuzu buraya yazın
df.groupby(['Sex','Pclass']).agg({'Survived':'mean'})

               Survived
Sex    Pclass
female 1       0.968085
       2       0.921053
       3       0.500000
male   1       0.368852
       2       0.157407
       3       0.135447

### Soru 4: Embarked değişkenine göre ortalama yaş ve ortalama ücret nedir?

In [16]:
# Kodunuzu buraya yazın
df.groupby(['Embarked']).agg({'Age' : 'mean', 'Fare' : 'mean'})

                Age       Fare
Embarked
C         30.814769  59.954144
Q         28.089286  13.276030
S         29.445397  27.079812

Cherbourg limanında satılan biletlerin 💸💸💸 olduğunu görüyoruz.

### Soru 5: Pclass gruplarına göre yaşın standart sapmasını bulun.

In [17]:
# Kodunuzu buraya yazın
df.groupby(['Pclass']).agg({'Age':'std'})

              Age
Pclass
1       14.802856
2       14.001077
3       12.495398

### Soru 6: Her `Embarked` limanından kaç yolcu olduğunu ve bunların yüzdelik dağılımını yazdırın.

In [26]:
# Kodunuzu buraya yazın
TravellerCount = df['Embarked'].value_counts()
print(TravellerCount)

df['Embarked'].value_counts(normalize=True)

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

Embarked
S    0.724409
C    0.188976
Q    0.086614
Name: proportion, dtype: float64

### Soru 7: Yaşı 60'tan büyük olanların hayatta kalma oranını bulun.

In [28]:
# Kodunuzu buraya yazın
df[df['Age'] > 60].agg({'Survived':'mean'})

Survived    0.227273
dtype: float64

### Soru 8: `Sex`, `Pclass`, `Survived` için `groupby()` + `agg()` ile ortalama yaş ve ücret hesaplayın.

In [29]:
# Kodunuzu buraya yazın
df.groupby(['Sex','Pclass','Survived']).agg({'Age':'mean','Fare':'mean'})

                              Age        Fare
Sex    Pclass Survived
female 1      0         25.666667  110.604167
              1         34.939024  105.978159
       2      0         36.000000   18.250000
              1         28.080882   22.288989
       3      0         23.818182   19.773093
              1         19.329787   12.464526
male   1      0         44.581967   62.894910
              1         36.248000   74.637320
       2      0         33.369048   19.488965
              1         16.022000   21.095100
       3      0         27.255814   12.204469
              1         22.274211   15.579696

Burada bariz bir şekilde kadın ve erkek biletlerinde -özellikle 1.sınıf biletlerde- bir fark görüyoruz.

### Soru 9: Age değişkenini artan düzende sıralayın ve ilk 10 kişiyi yazdırın.

In [32]:
# Kodunuzu buraya yazın
df.sort_values(by='Age',ascending=False).head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C

En yaşlı yolcumuz 80 yaşındaki 🧓 Henry Dede'ymiş.

---
# 🧠 KİRLENMEK GÜZELDİR SORULARI :)
---

### Soru 1: En pahalı bileti alan kişinin yaşı, cinsiyeti ve sınıfı nedir?

In [35]:
# Kodunuzu buraya yazın
df[df['Fare']==df['Fare'].max()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

### Soru 2: Hayatta kalanlar ile ölenler arasında yaş ortalamaları farkı nedir?

In [36]:
# Kodunuzu buraya yazın
df.groupby('Survived').agg({'Age':'mean'})

                Age
Survived
0         30.626179
1         28.343690

### Soru 3: Hangi `Pclass` grubunda kadınların hayatta kalma oranı en yüksektir?

In [45]:
# Kodunuzu buraya yazın
newDf = df[['Pclass', 'Sex', 'Survived']]
newDf[(df['Sex'] == 'female')].groupby('Pclass').agg({'Survived':'mean'})

        Survived
Pclass
1       0.968085
2       0.921053
3       0.500000

### Soru 4: Ortalama yaşın altında olan ve hayatta kalan erkeklerin sayısı kaçtır?

In [56]:
ortalama_yas = df['Age'].mean()
df[(df['Age'] < ortalama_yas) & (df['Survived'] == 1) & (df['Sex'] == 'male')].shape[0]

51

### Soru 5: `Cabin` değeri eksik olmayanların yaş ortalaması ile eksik olanların yaş ortalaması arasında fark var mı?

In [65]:
# Kodunuzu buraya yazın
kabinEksik = df[df['Cabin'].isnull()]
kabinEksikYasOrt = kabinEksik['Age'].mean()

kabinVar = df[df['Cabin'].notnull()]
kabinVarYasOrt = kabinVar['Age'].mean()

print(f"Cabin değeri eksik olanların yaş ortalaması: {kabinEksikYasOrt:.2f}")
print(f"Cabin değeri eksik olmayanların yaş ortalaması: {kabinVarYasOrt:.2f}")

Cabin değeri eksik olanların yaş ortalaması: 27.56
Cabin değeri eksik olmayanların yaş ortalaması: 35.83

Evet fark var

### Soru 6: `.describe()` çıktısına göre çarpıklık var mı? Hangi değişkenlerde?

In [57]:
# Kodunuzu buraya yazın
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Evet var 512$ 'lık bilet ortalama + standart sapma değerinden bile büyük olduğu için bizim için aykırı bir veridir.

### Soru 7: Veri setindeki en fazla tekrarlanan yaş değeri (mod) nedir?

In [59]:
# Kodunuzu buraya yazın
df.agg({'Age':'mode'})

    Age
0  24.0

### Soru 8: Ortalama bilet fiyatı kadınlar mı yoksa erkekler için mi daha yüksek?

In [66]:
# Kodunuzu buraya yazın
df.groupby('Sex').agg({'Fare':'mean'})

             Fare
Sex
female  44.479818
male    25.523893

Hem de neredeyse 2 katı fark var